name: Build Project

on: 
  pull_request:
  push:
    branches: main
  workflow_dispatch:

jobs:
  build:
    name: Build App
    runs-on: windows-latest
    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Cache Docker Image (Restoration before checking)
      - name: Cache Docker Image
        uses: actions/cache@v4
        with:
          path: C:\docker-cache\image.tar
          key: docker-windows-unityci
          restore-keys: |
            docker-windows-unityci

      # Restore Cached Docker Image
      - name: Restore Cached Docker Image
        run: |
          if (Test-Path "C:\docker-cache\image.tar") {
            docker load -i C:\docker-cache\image.tar
          }
        shell: powershell

      # Cache Unity Library
      - uses: actions/cache@v4
        with:
          path: Library
          key: Library
          restore-keys: |
            Library

      # Build
      - name: Build App
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: StandaloneWindows64
          buildName: ChuniXR
          buildsPath: exported
          customParameters: '-debugSymbols false'

      # Cache built project to avoid re-uploading unchanged builds
      # - uses: actions/cache@v4
      #   with:
      #     path: exported
      #     key: build-output-${{ github.sha }}

      # Remove debug symbols (ChuniXR_BackUpThisFolder_ButDontShipItWithYourGame)
      - name: Remove Debug Symbols
        run: |
          $debug_symbols_path = "exported/StandaloneWindows64/ChuniXR_BackUpThisFolder_ButDontShipItWithYourGame"
          if (Test-Path $debug_symbols_path) {
            Remove-Item -Recurse -Force $debug_symbols_path
            Write-Host "Debug symbols folder removed."
          } else {
            Write-Host "Debug symbols folder not found."
          }
        shell: powershell
      
      # Upload exported build
      - uses: actions/upload-artifact@v4
        with:
          name: Exported
          path: exported
          compression-level: 0  # Faster uploads
